name: "Dagger basic example"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2     

      - name: "Install Dagger"
        uses: dagger/dagger-for-github@v4
        with:
          install-only: true
      - name: "Execute dagger"
        working-directory: ./basic
        run: |
          cd dagger && npm install
          cd .. && node dagger/basic.mjs
