name: "Dagger Export"

on:
  workflow_dispatch:
    
env:
  
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2     

      - name: "Run Dagger"
        uses: dagger/dagger-for-github@v4
        working-directory: ./basic
        with:
          cmds: do test
